apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # запускает 3 пода, созданных по шаблону
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.21.1-apline
        ports:
          
            - containerPort: 80
            #  command: ['sh', '-c', 'echo Hello Kubernetes from the Deployment! && sleep 3600']
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx/
        env:
        - name: NGINX_USERNAME
          valueFrom:
            secretKeyRef:
              name: sf-auth-nginx
              key: user1
        
        - name: NGINX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sf-auth-nginx
              key: password1
  
              
      volumes:
        - name: config-volume
          configMap:
            name: config-nginx         

---
kind: Service
apiVersion: v1
metadata:
  name: sf-webserver
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


---

apiVersion: v1
kind: Secret
metadata:
  name: auth_basic
type: kubernetes.io/basic-auth
stringData:
  username: user1 # required field for kubernetes.io/basic-auth
  password: pasword1 # required field for kubernetes.io/basic-auth
